# Generated by Django 3.1.4 on 2021-01-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('pan_no', models.CharField(max_length=50)),
                ('aadhar_no', models.CharField(max_length=50)),
                ('pan_card_photo', models.ImageField(upload_to=None)),
                ('aadhar_card_photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
