# Generated by Django 3.1.4 on 2021-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210122_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalows_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('longitude', models.IntegerField(max_length=100)),
                ('latitude', models.IntegerField(max_length=100)),
                ('ground_area', models.CharField(max_length=50)),
                ('carpet_area', models.CharField(max_length=50)),
                ('BedHK', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
    ]
