# Generated by Django 3.1.4 on 2021-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_bungalows_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bungalows_info',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
