# Generated by Django 3.1.4 on 2021-01-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20210124_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flats_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('ground_area', models.CharField(max_length=50)),
                ('carpet_area', models.CharField(max_length=50)),
                ('flate_name', models.CharField(max_length=50)),
                ('flate_no', models.CharField(max_length=50)),
                ('BedHK', models.CharField(max_length=50)),
                ('floor_no', models.CharField(max_length=50)),
                ('car_parking', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
