# Generated by Django 3.1.4 on 2021-01-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_flats_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_date', models.CharField(max_length=50)),
                ('appoint_time', models.CharField(max_length=50)),
                ('buyer_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.buyer')),
                ('seller_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.seller_info')),
            ],
        ),
    ]
