# Generated by Django 3.1.4 on 2021-01-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_appointment_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalows_infoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('ground_area', models.CharField(max_length=50)),
                ('carpet_area', models.CharField(max_length=50)),
                ('BedHK', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flats_infoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('ground_area', models.CharField(max_length=50)),
                ('carpet_area', models.CharField(max_length=50)),
                ('flate_name', models.CharField(max_length=50)),
                ('flate_no', models.CharField(max_length=50)),
                ('BedHK', models.CharField(max_length=50)),
                ('floor_no', models.CharField(max_length=50)),
                ('car_parking', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Appointment_db',
            new_name='Appointment_dba',
        ),
        migrations.RenameModel(
            old_name='Seller_info',
            new_name='Buyera',
        ),
        migrations.DeleteModel(
            name='Bungalows_info',
        ),
        migrations.DeleteModel(
            name='Flats_info',
        ),
        migrations.RenameModel(
            old_name='Buyer',
            new_name='Seller_infoa',
        ),
        migrations.AddField(
            model_name='flats_infoa',
            name='seller_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.seller_infoa'),
        ),
        migrations.AddField(
            model_name='bungalows_infoa',
            name='seller_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.seller_infoa'),
        ),
    ]
