# Generated by Django 3.1.4 on 2021-01-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20210128_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment_dba',
            new_name='Appointment_db',
        ),
        migrations.RenameModel(
            old_name='Bungalows_infoa',
            new_name='Bungalows_info',
        ),
        migrations.RenameModel(
            old_name='Seller_infoa',
            new_name='Buyer',
        ),
        migrations.RenameModel(
            old_name='Flats_infoa',
            new_name='Flats_info',
        ),
        migrations.RenameModel(
            old_name='Buyera',
            new_name='Seller_info',
        ),
    ]
