# Generated by Django 3.1.4 on 2021-01-27 20:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20210128_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bungalows_info',
            name='seller_db',
        ),
        migrations.AddField(
            model_name='bungalows_info',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='seller_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.seller_info'),
        ),
    ]
