# Generated by Django 3.1.4 on 2021-01-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20210128_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flats_info',
            name='seller_db',
        ),
    ]
