# Generated by Django 3.1.4 on 2021-02-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats_info',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
