# Generated by Django 3.1.4 on 2021-02-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20210206_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats_info',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='first_app.seller_info'),
        ),
    ]
