# Generated by Django 3.1.4 on 2021-02-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_remove_flats_info_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_db',
            name='buyer_db',
        ),
        migrations.RemoveField(
            model_name='appointment_db',
            name='seller_db',
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.RemoveField(
            model_name='flats_info',
            name='pic',
        ),
        migrations.DeleteModel(
            name='Appointment_db',
        ),
    ]
