# Generated by Django 3.1.4 on 2021-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_auto_20210206_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats_info',
            name='pic',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
