# Generated by Django 3.1.4 on 2021-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_flats_info_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bungalows_info',
            name='pic',
            field=models.ImageField(default='', upload_to='media/bungalows_img'),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='pic',
            field=models.ImageField(default='', upload_to='media/flats_img'),
        ),
    ]
