# Generated by Django 3.1.4 on 2021-02-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_bungalows_info_seller_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bungalows_info',
            old_name='seller_db',
            new_name='gmail_id',
        ),
    ]
