# Generated by Django 3.1.4 on 2021-02-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_auto_20210207_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bungalows_info',
            name='gmail_id',
        ),
    ]
