# Generated by Django 3.1.4 on 2021-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_remove_bungalows_info_gmail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='aadhar_card_photo',
            field=models.ImageField(default='', upload_to='media/seller_img'),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='aadhar_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='pan_card_photo',
            field=models.ImageField(default='', upload_to='media/seller_img'),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='pan_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='seller_profile',
            field=models.ImageField(default='', upload_to='media/seller_img'),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='BedHK',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='carpet_area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='ground_area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bungalows_info',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='gmail_id',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='BedHK',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='car_parking',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='carpet_area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='flate_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='flate_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='floor_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='ground_area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flats_info',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='gmail_id',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
