# Generated by Django 3.1.4 on 2021-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_flats_info_property_image_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats_info',
            name='property_image_four',
            field=models.ImageField(default='', upload_to='media/flats_img'),
        ),
        migrations.AddField(
            model_name='flats_info',
            name='property_image_three',
            field=models.ImageField(default='', upload_to='media/flats_img'),
        ),
        migrations.AddField(
            model_name='flats_info',
            name='property_image_tow',
            field=models.ImageField(default='', upload_to='media/flats_img'),
        ),
    ]
